### ISSUE TITLE
How to build docs of QuantLibAddin?

### ISSUE THREAD

**Issue by xuruilong100** [eehlers/QuantLibAddin-Old#28]
I build project `docs-QuantLibAddin` in solution `QuantLibAllDynamic`, then get

```
1>NMAKE : fatal error U1077: '..\..\ObjectHandler\Docs\preprocess_doxyfile.py' : return code '0x1'
1>Stop.
1>D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets(45,5): error MSB3073: The command "NMAKE /f Makefile.vc" exited with code 2.
1>Done building project "docs-QuantLibAddin.vcxproj" -- FAILED.
```

**Comment by eehlers** [comment]
Do you have doxygen and python installed?

What happens if you try to run the relevant command at a DOS prompt, outside of Visual Studio and make?

**Comment by xuruilong100** [comment]
> Do you have doxygen and python installed?
> 
> What happens if you try to run the relevant command at a DOS prompt, outside of Visual Studio and make?

Hi, I have installed doxygen and python, and added them to `PATH`.

It seems that `PYTHON` is forgotten to declare here, so I complete it as follow,

```
PYTHON=python.exe

$(BUILDFLAG) : $(DEPENDENCIES) $(BUILD_DIR) $(IMG_DIR) $(DOXY_CONFIG)
    copy /Y tabs.css $(HTML_DIR)
    copy /Y ql.css $(HTML_DIR)
    copy /Y images\* $(IMG_DIR)
    $(PYTHON) $(SCRIPT) $(DOXY_CONFIG) $(DOXY_CONFIG_TEMP)
	$(DOXYGEN) $(DOXY_CONFIG_TEMP)
    del $(DOXY_CONFIG_TEMP)
	echo flagged > $@
```

Finally, it works.

**Comment by eehlers** [comment]
Please refer to this page...

https://www.quantlib.org/quantlibaddin/build_qlxl.html

...item 2.3.  On some machines, the location of python is not known and you have to add it to the file.
